/* Generated by ffmpeg configure — hier von Hand gesetzt.
 * x86-64/ARM64 Linux: Little Endian, schnelle unausgerichtete Zugriffe.
 * Beides gilt für jede Plattform, auf der HoneyCord unter Linux läuft. */
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define AV_HAVE_FAST_UNALIGNED 1
#endif /* AVUTIL_AVCONFIG_H */
